services:
  # MCP Proxy service - configurable transport via .env
  mcp-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./servers.json:/app/servers.json:ro
    environment:
      - TZ=${TZ}
      - TRANSPORT=${TRANSPORT}
      - HOST=${HOST}
      - PORT=${PORT}
      - CHANNEL_ACCESS_TOKEN=${CHANNEL_ACCESS_TOKEN}
      - DESTINATION_USER_ID=${DESTINATION_USER_ID}
      - EXA_API_KEY=${EXA_API_KEY}